-- Import Lua modules
-- not using for loop so I could jump to file using LSP
require("packer_init")
require("core.autocmds")
require("core.colors")
require("core.keymaps")
require("core.options")
require("core.statusline")
require("plugins.alpha-nvim")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.indent-blankline")
require("plugins.lsp")
require("plugins.nvim-cmp")
require("plugins.nvim-tree")
require("plugins.nvim-treesitter")
require("plugins.tabby")
require("plugins.telescope")
require("plugins.toggleterm")
require("plugins.todo-comments")
require("plugins.gitsigns")
require("plugins.hop")
require("plugins.nvim_surround")
