-- Import Lua modules

require("packer_init")
require("core.autocmds")
require("core.colors")
require("core.keymaps")
require("core.options")
require("core.statusline")
require("plugins.alpha-nvim")
require("plugins.autotag")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.leap")
require("plugins.indent-blankline")
require("plugins.lsp")
require("plugins.mini-nvim")
require("plugins.nvim-cmp")
require("plugins.nvim-surround")
require("plugins.nvim-tree")
require("plugins.nvim-treesitter")
require("plugins.telescope")
require("plugins.todo-comments")
require("plugins.toggleterm")
