-- Import Lua modules
require('packer_init')
require('core/options')
require('core/autocmds')
require('core/keymaps')
require('core/colors')
require('core/statusline')
require('plugins/alpha-nvim')
require('plugins/indent-blankline')
require('plugins/nvim-tree')
require('plugins/nvim-cmp')
require('plugins/nvim-lspconfig')
require("plugins/telescope")
require('plugins/nvim-treesitter')
require("plugins/comment")
